 apiVersion: v1  
 kind: Service  
 metadata:  
   name: rackweb
   labels:  
     app: rackweb
   #namespace: default  
 spec:  
   ports:  
   - name: rackweb
     port: 80  
     targetPort: 9292
     protocol: TCP
   selector:  
     app: rackweb

# kubectl create -f svc.yml
