 apiVersion: v1  
 kind: Service  
 metadata:  
   name: nginx
   labels:  
     app: nginx
   #namespace: default  
 spec:  
   ports:  
   - name: nginx
     port: 80  
     targetPort: 80  
     protocol: TCP
   selector:  
     app: nginx

# kubectl create -f svc.yml
