version: '2'
services:
  web:
    image: nginx
    volumes:
      #- "nfsmount:${CONTAINER_DIR}"
      - "nfsmount:/myapp"

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      #device: ":${SOURCE_DIR}"
      device: ":/Users/caoruijian/dev"