kind: PersistentVolume
apiVersion: v1
metadata:
  name: microxs-commerce-jenkins-volume-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /Users/kbdata/test2
