version: "3.0"
services:
  registry:
    image: registry:2
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    environment:
      #- REGISTRY_LOG_LEVEL=debug
      - REGISTRY_HTTP_ADDR=:5000
      #- REGISTRY_HTTP_HOST=http://registry.dk:5000
      #- REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
      #- REGISTRY_PROXY_USERNAME=cao7113
      #- REGISTRY_PROXY_PASSWORD=cao5689452
      #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      #REGISTRY_AUTH: htpasswd
      #REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      #REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /Volumes/docker/docker-registry:/var/lib/registry
      #- /path/certs:/certs
      #- /path/auth:/auth
  #webui:
    # https://github.com/kwk/docker-registry-frontend
    #image: konradkleine/docker-registry-frontend:v2
    #container_name: registry-ui
    #restart: always
    #ports:
      #- 8080:80
    #environment:
      #- ENV_DOCKER_REGISTRY_HOST=localhost
      #- ENV_DOCKER_REGISTRY_PORT=5000

#networks:
  #default:
    #external:
      #name: dev-net
