apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging

#kubectl delete namespaces <insert-some-namespace-name>
# kubectl create -f ./staging.yml
# kubectl delete -f ./staging.yml