version: '2'

services:
  metabase:
    restart: always
    image: metabase/metabase
    container_name: 'metabase'
    expose:
      - "3000"
    environment:
    - MB_DB_TYPE=postgres
    - MB_DB_DBNAME=metabase
    - MB_DB_PORT=5432 
    - MB_DB_USER=postgres
    - MB_DB_PASS=
    #- MB_DB_HOST=docker.for.mac.localhost
    - MB_DB_HOST=pgdb

    #- JAVA_TIMEZONE=US/Pacific
    - JAVA_TIMEZONE=Asia/Shanghai
    # nginx vhost
    - VIRTUAL_HOST=metabase.lh,bi.lh

networks:
  default:
    external:
      name: dev-net
